### ISSUE TITLE
Feature request: possibility to make files accessible only locally

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#130]
The digitization department have asked, if it would be possible to make certain works accessible just within a certain IP domain. 
A possible solution to this problem would be to replace the enabled attribute with something like "accessibility". This accessibility field could e.g. contain an ENUM with {global, local, none}, where local should be configured to an IP domain. Another possibility would be to allow strings in the accessibility field, which would make it possible to explicitly set different IP domains for different cases. This solution would however be harder to maintain and more error-prone. And i suppose the first solution would be sufficient.
Even better ideas are of course also welcone. ;)

**Comment by ponchofiesta** [comment]
I think about this:

```yaml
fileserver:
  access:
    - global: 0.0.0.0/32
    - tu: 130.149.0.0/16,141....
    - ub: ....
```
These `access` entries are defined by the user - we could provide `global` and `none` by default. So the user could define multiple access levels or regions. 

The Work entitiy will have a field access with name of the region from the YAML file.

The downside is, if one entry is removed or renamed it is not found by the fileserver anymore. So there should be some way to handle this case.

Otherwise the enum idea is good.

**Comment by ponchofiesta** [comment]
OK, the user may now set networks in the _ local.yml_. These two are in _ default.yml_ :

```yaml
  allowedNetworks:
    global: 0.0.0.0/0,::/0
    none: 0.0.0.0/32,::/128
```

IPv4 and IPv6 are supported. In the web UI the user can set the access rule by selecting some works and use _Action_ -> _Network access rule_ -> select the network. The current network is shown before the action buttons on every work. If the work doesn't have a valid network the HTTP access will be blocked for everyone.
The `Work` entity got a new field `allowedNetwork` which stores the network name from the _local.yml_ file
