### ISSUE TITLE
General solution for loading of resource files

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#90]
The loading of classpath files behaves differently when running in jar or war or starting the spring boot plugin. We need a general solution that works for all these cases.
SImply working with input stream instead of file will not work when loading a resource in a bean, since the input stream will be closed after the first usage.

**Comment by ponchofiesta** [comment]
I think about two workarounds:
- A function MediaserverUtils.getResourceStream(String resourceName) which tries to open the resource on every call with different methods (classpath, classpath*, new ClassPathResource()). One will hopefully work. Springs ResourceUtils tests different ways too. I think this way a File is not needed.
- If we still need a File or a static resource which could be read multiple times, we could do the same way as above and copy the resource to a String or a temporary file and return it instead of the stream.

Maybe we should not work work with a File in beans but with our MediaserverUtils which can return a fresh InputStream everytime it is called. All this is not that nice and really only a workaround but if it will work in all situations, I think it'll be OK.

**Comment by pbroman** [comment]
We have this problem only by loading xslt files from classpath, this is currently only done by the XsltMetsReader. A simpler solution is thus to let the mets file by a ClassPathResource instead of a File object. The only drawback is that then you cannot use an externel xslt from the file system, you have to have them on the class path. But if somebody wishes to load alternative xslt files, this person will probably wish to test the files and there impackt as well, thus adding the files to the project rather than just having them in the file system, so I think we could live with this solution.
We should however add a possibility to configure which xslt files should be loaded.
